USE TOTVSDB

SELECT 
    T1.CYV_CDMQ AS "Codigo_Maquina"
    , T2.CYB_DSMQ AS "Descricao_Maquina"
    , T1.CYV_QTATRP AS "Quantidade_Atropelamento"
	, T6.OX_DESCR AS "Produto"
    , T1.CYV_DTRPBG AS "Data_Registro"
    , T1.CYV_HRRPBG AS "Hora_Registro"
    , T1.CYV_CDUSRP AS "Usuario_Registro"
    , COALESCE(
        CASE WHEN CHARINDEX(T1.CYV_CDUSRP, T3.X6_CONTEUD) > 0 THEN 'Fabrica 1' END,
        CASE WHEN CHARINDEX(T1.CYV_CDUSRP, T4.X6_CONTEUD) > 0 THEN 'Fabrica 2' END,
        'Não identificado'
      ) AS "Fabrica"
FROM CYV000 (NOLOCK) AS T1
JOIN CYB000 (NOLOCK) AS T2 ON T1.CYV_FILIAL = T2.CYB_FILIAL AND T1.CYV_CDMQ = T2.CYB_CDMQ AND T2.D_E_L_E_T_ <> '*'
LEFT JOIN SX6000 (NOLOCK) AS T3 ON T3.X6_VAR = 'MV_X_USRF1'
LEFT JOIN SX6000 (NOLOCK) AS T4 ON T4.X6_VAR = 'MV_X_USRF2'
JOIN V9_000 (NOLOCK) AS T5 ON T1.CYV_CDMQ = T5.V9__MAQ AND T1.CYV_NRORPO = T5.V9__OP AND T1.CYV_DTRPBG = T5.V9__DTINI and T1.CYV_HRRPBG = T5.V9__HRINI AND T5.V9__STATUS = 1 AND T5.D_E_L_E_T_ <> '*'
JOIN SOX000 (NOLOCK) AS T6 ON T5.V9__FORM = T6.OX_FORM AND T6.D_E_L_E_T_ <> '*'
WHERE T1.D_E_L_E_T_ <> '*' AND T1.CYV_FILIAL = '0101' AND T1.CYV_CDMQ LIKE 'RET%' AND T1.CYV_DTRPBG BETWEEN '20240430' AND '20240601'
ORDER BY T1.CYV_DTRPBG, T1.CYV_CDMQ, T1.CYV_HRRPBG